### PR TITLE
fix(): refreshing hooks on show context menu

### PR DESCRIPTION
**Pull request by andreabadesso**
Fixes glitch where if the contextMenu is added dynamically, like this:

```
                mapMenu = new L.Map.ContextMenu(map);
                mapMenu.addItem({
                    text: 'Random text',
                    callback: function(e) {
                        // Do something
                    }
                });
                mapMenu.addHooks();
```

The context menu would lose the hooks when being added to another marker

### CODE REVIEW

**Comment by aratcliffe** [comment]
If the map is initialised with the option `contextmenu: true` the context menu interaction handler is created for you. Options like `contextmenuWidth` can only be set through the map options so I'm not sure why you would want to create the context menu like this?

**Comment by andreabadesso** [comment]
I'm using this because I'm using angular-leaflet, so I don't control the map creation

**Comment by aratcliffe** [comment]
I've added an example using angular-leaflet showing how to configure the context menu using the directive `defaults`.

**Comment by andreabadesso** [comment]
Thank you

**Pull request closed without merging**
